@"
    #MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXOkOKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM TODO: Remove shameless branding
    #MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNk:`````;dKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    # MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO;``````````oNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM Follow us on Social Media
    # MMMMMMMMMMMMMMMMMMMMMMMMMMMMMk,````;dO00ko;:0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM L: company/compsec-direct
    # MMMMMMMMMMMMMMMMMMMMMMMMMMMWd````,oNMMMMMMNo,kMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM T: @CompSecDirect / @jfersec
    # MMMMMMMMMMMMMMMMMMMMMMMMMMMk````,kMMMMMMMMMWk:KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM FB: /CompSecDirect/
    # MMMMMMMMMMMMMMMMMMMMMMMMMMX;````kMMMMMMMMMMMMKlNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    # MMMMMMMMMMMMMMMMMMMMMMMMMMo````dWMMMMMMMMMMMMMOoWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    # MMMMMMMMMMMMMMMMMMMMMMMMMO,```lWMMMMMMMMMMMMMMMO0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    # MMMMMMMMMMMMMMMMMMMMMMMMN:```,KMMMMMMMMMMMMMMMMMKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    # MMMMMMMMMMMMMMMMMMMMMMMMk````lMMMMMMMMMMMMMMMMMMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    # MMMMMMMMMMMMMMMMMMMMMMMMc````0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    # MMMMMMMMMMMMMMMMMMMMMMMK,```cWMMMMMMMMMMMMMWNXKKKXNWMMMMMMMMMMMMMMMMMMMMMMMMMMM
    # MMMMMMMMMMMMMMMMMMMMMMMk````OMMMMMMMMMMMMWKkkkkkkkkkKWMMMMMMMMMMMMMMMMMMMMMMMMM
    # MMMMMMMMMMMMMMMMMMMMMMMo```;NMMMMMMMMMMMNkkkkkkkkkkkkONMMMMMMMMMMMMMMMMMMMMMMMM
    # MMMMMMMMMMMMMMMMMMMMMMW:```oMMMMMMMMMWOX0kkkkkkkkkkkkkKMMMMMMMMMMMMMMMMMMMMMMMM
    # MMMMMMMMMMMMMMMMMMMMNOo,```lKNMMMMNKx:`K0kkkkkkkkkkkkkKMMMMMMMMMMMMMMMMMMMMMMMM DISABLE folder execution FROM jfersec @CompSecDirect
    # MMMMMMMMMMMMMMMMMMXo;````````,;::;,````oNOkkkkkkkkkkkkk0XWMMMMMMMMMMMMMMMMMMMMM Version 0.1, Rapid proof
    # MMMMMMMMMMMMMMMMMN:```````````````,lk0KXWMKkkkkkkkkkkkkkkkKNMMMMMMMMMMMMMMMMMMM Date Aug 26, 2022
    # MMMMMMMMMMMMMMMMMk``````````````;kNMMMMMMMM0kkkkk0NWWX0kkkkkOXWMMMMMMMMMMMMMMMM
    # MMMMMMMMMMMMMMMMM0`````````````cXMMMMMMMMMMNkkkkKMMMMMMNKkkkkkkKWMMMMMMMMMMMMMM MIT License, StreamWare
    # MMMMMMMMMMMMMMMMMMd,``````````oNNMMMMMMMMMMNkkk0MMMMMMMMMWKOkkkkk0NMMMMMMMMMMMM No ownership rights expressed
    # MMMMMMMMMMMWXWMMMMMKd;`````,lO0ooXMMMMMMMMM0kkxXMMMMMMMMMMMMNOkkkkk0NMMMMMMMMMM Make this script not suck: Hit up github
    # MMMMMMMMMN0KWMMMMMMMMWXK00KXKxccccd0XWMMMMNKK0O0MMMMMMMMMMMMMMN0kkkkk0WMMMMMMMM Github: github.com/CompSecDirect/dfir
    # MMMMMMMW0kNMMMMMMMMMMMMMMMMMMMN0xcccclodddoodk0XWMMMMMMMMMMMMMMMNOkkkkkKWMMMMMM
    # MMMMMMKdOWMMMMMMMMMMMMMMMMMMMMMMMKocccccccccccclOWMMMMMMMMMMMMMMMMXkkkkkONMMMMM Suggested by: TheThreatHunter
    # MMMMMOlKMMMMMMMMMMMMMMMMMMMMMMMMMMWdcccccccccccccOMMMMMMMMMMMMMMMMMNOkkkkkNMMMM
    # MMMWxc0MMMMMMMMMMMMMMMMMMMMMMMMMMMM0cccccccccccccdMMMMMMMMMMMMMMMMMMW0kkkkkXMMM
    # MMMxclNMMMMMMMMMMMMMMMMMMMMMMMMNKkdlccccccccccccckMMMMMMMMMMMMMMMMMMMNkkkkkOMMM
    # MMKcccKMMMMMMMMMMMMMMMMMMWN0OxocccccccccccccccccdNMMMMMMMMMMMMMMMMMMMWkkkkkkWMM
    # MMkccclkKNWWMMMWWNXK0OkxolccccccccoxOK0dlccccokKWMMMMMMMMMMMMMMMMMMMN0kkkkkKMMM
    # MMOcccccccclllllcccccccccccccoxOKWMMMMMMWNNNWMMMMMMMWWWNNXXXXXXXXK0OkkkkOKNMMMM
    # MMWklcccccccccccccccclodkO0XWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNNXXXXXXXNWWMMMMMMM
    # MMMMWX0kxxdddxxkOOKXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    # MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
"@

# Step 1 : Prompt
$Folder = Read-Host "Enter folder to mark as non-executable"
# Step 2: Check if valid
if (Test-Path -Path $Folder)
# Step 3: Execute
{
    $command = "icacls $Folder /deny 'Everyone:(OI)(IO)(X)'"
    iex $command
}